name: Justin Lester
favicon: null
layout_spectrum: 0.00875
typography_spectrum: 0.84926
title: ForeverLester
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfaf6'
    - '#10142b'
    - '#2b3a4f'
    - '#a2acb4'
    - '#747b8a'
  brandStrength: 0.7394863376393914
  lightness: 0.7810964214149863
  saturation: 0.11465906002558768
  rhythmicContrast: 0.4362668846733868
purpose: []
